spring.datasource.url= jdbc:sqlserver://localhost:1433;databaseName=DoAnTotNghiep;trustServerCertificate=true;username=sa;password=123456;

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto= update
spring.datasource.connectionProperties=useUnicode=true;characterEncoding=utf-8;
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

#Paypal config
paypal.mode=sandbox
paypal.client.app=ASs44Zzuzxd1Pgx-KflljtetA5zM2ICn9EFg69JHk9XfEBR7aB8kbYV0ggjdy1H3rIx84GCJZhRcyxAT
paypal.client.secret=EMq0jol4U35egVNrEe1Kosz1TadAx2POd56o_R_uVu1cq5muO7oq4eajrZsOthgNeXJKu1hKWEp9EKmC

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leducthiet125@gmail.com
spring.mail.password=rbzuvudhbevykwai
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

