spring.datasource.url= jdbc:sqlserver://localhost:1433;databaseName=DoAnTotNghiep;trustServerCertificate=true;username=sa;password=123456;

spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.SQLServer2012Dialect
spring.jpa.hibernate.ddl-auto= update
